#! /bin/sh
# Run the Lisp test scripts
#
# Copyright (c) 2005 Reuben Thomas.
# All rights reserved.
#
# This file is part of Zee.
#
# Zee is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# Zee is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with Zee; see the file COPYING.  If not, write to the Free
# Software Foundation, 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.  */

for i in test1 test2 test3; do
  ./zee -q --batch --load=$i.el > $i.stdout
  if ! diff $i.stdout $i.output; then
    exit 1
  fi
done
