\input texinfo   @c -*-texinfo-*-
@setfilename zee.info
@settitle The Zee Manual

@dircategory Text editors
@direntry
* Zee: (zee).                 Zee text editor.
@end direntry

@iftex
@finalout
@end iftex

@setchapternewpage odd

@titlepage
@title The Zee Manual
@subtitle for Zee version 0.7
@subtitle August 2007
@author Reuben Thomas

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2003-2006 Reuben Thomas
Copyright @copyright{} 2005 Alistair Turnbull
Copyright @copyright{} 1997-2004 Sandro Sigala
Copyright @copyright{} 2004 David A. Capello
@end titlepage

@c ---------------------------------------------------------------------------
@node Top, Overview, (dir), (dir)

This is the @emph{Zee} manual.

Zee is an experimental editor and programming environment.

@menu
* Overview::                    An overview of the Zee editor.
* Invoking Zee::                Command line options that you can give to Zee.
* Initialization file::         The ``.zeerc'' initialization file.
* Key names::                   How the keys are named.
* Commands::                    The list of commands.
* Variables::                   The list of variables.
* Bug reports::                 How to report a bug.
@end menu

@c ---------------------------------------------------------------------------
@node Overview, Invoking Zee, Top, Top
@chapter Overview

Zee is an experimental editor, hosted on SourceForge at
@uref{http://sourceforge.net/projects/zee/}. It is free software,
licensed under the GNU GPL.

Zee is written in ISO C99 for POSIX and requires the Boehm garbage
collector (libgc), PCRE (the Perl-compatible regular expressions
library), and a terminal library (either ncurses or Allegro).

@c ---------------------------------------------------------------------------
@node Invoking Zee, Initialization file, Overview, Top
@chapter Invoking Zee

The options are as follows:

@include opts.texi

@c ---------------------------------------------------------------------------
@node Initialization file, Key names, Invoking Zee, Top
@chapter Initialization file

When Zee is started, it normally loads the @file{.zeerc} file in your
home directory. We call this file your ``initialization file'' because
it specifies how to initialize Zee for you.

@menu
* File syntax::                 The initialization file syntax.
@end menu

@c ---------------------------------------------------------------------------
@node File syntax, , Initialization file, Initialization file
@section File syntax

The initialization file is a sequence of commands. The file is most
commonly used to initialize variables and to bind keys.

FIXME: add example file, and refer to Lua manual.

@c ---------------------------------------------------------------------------
@node Key names, Commands, Initialization file, Top
@chapter Key names

This table contains the names of the keys that are used in Zee.

@table @key
@item SPC
Space
@item RET
Return
@item TAB
Tab
@item BS
Backspace
@item ESC
Escape
@item DEL
Delete
@item CTRL
Control
@item ALT
Alt
@end table

In key combinations, like @kbd{Alt-G}, the @kbd{Alt-} prefix means
hold the @key{ALT} key down while typing @kbd{g}. The combination
@kbd{Ctrl-X} means hold the @key{CTRL} key down while typing @kbd{x}.

@c ---------------------------------------------------------------------------
@node Commands, Variables, Key names, Top
@chapter Commands

This table contains the full list of available commands that can be
called with the @kbd{Alt-X} key (please note that most commands have a
key binding anyway).

@include funcs.texi

@c ---------------------------------------------------------------------------
@node Variables, Bug reports, Commands, Top
@chapter Variables

This table contains the full list of available variables, that can be
modified at run-time with the @samp{preferences_set_variable} command
or set at start-up in the @file{.zeerc} initialization file.

@include vars.texi

@c ---------------------------------------------------------------------------
@node Bug reports,  , Variables, Top
@chapter Bug reports

Any questions, comments, or bug reports should be sent to the
developers at @email{zee-devel@@lists.sourceforge.net}, or even better,
filed in the relevant tracker at @uref{http://sourceforge.net/projects/zee/}.

@contents

@bye

Local Variables:
compile-command: "texi2dvi zee.texi"
End:
