call_command ("insert", "(")
call_command ("end-of-line")
call_command ("insert", ")")
call_command ("backward-sexp")
call_command ("delete-char", "1")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
