call_command ("describe-variable", "tab-width")
call_command ("other-window", "1")
call_command ("edit-select-on", "point")
call_command ("forward-line", "1")
call_command ("move-next-word", "-4")
call_command ("edit-copy", "mark", "point")
call_command ("other-window", "-1")
call_command ("edit-paste")
call_command ("file-save")
call_command ("file-quit")
