call_command ("move-next-character")
call_command ("move-next-character")
call_command ("move-next-character")
call_command ("move-next-character")
call_command ("edit-delete-horizontal-space")
call_command ("file-save")
call_command ("file-quit")
