call_command ("edit-select-on", "point")
call_command ("move-next-character", "4")
call_command ("edit-copy", "mark", "point")
call_command ("edit-paste")
call_command ("file-save")
call_command ("file-quit")
