call_command ("edit-insert-newline-and-indent")
call_command ("forward-line")
call_command ("edit-insert-newline-and-indent")
call_command ("forward-line")
call_command ("edit-insert-newline-and-indent")
call_command ("edit-insert-newline-and-indent")
call_command ("file-save")
call_command ("file-quit")
