call_command ("edit-select-on", "point")
call_command ("move-next-line")
call_command ("move-next-line")
call_command ("edit-kill-selection", "point", "mark")
call_command ("move-next-line")
call_command ("move-next-line")
call_command ("move-next-line")
call_command ("edit-paste")
call_command ("file-save")
call_command ("file-quit")
