call_command ("forward-line")
call_command ("move-next-word", "2")
call_command ("edit-kill-line")
call_command ("forward-line", "2")
call_command ("edit-kill-line", "-1")
call_command ("forward-line", "-2")
call_command ("move-end-line")
call_command ("edit-kill-line", "0")
call_command ("file-save")
call_command ("file-quit")
