call_command ("edit-delete-next-character")
call_command ("edit-delete-next-character")
call_command ("edit-delete-next-character")
call_command ("edit-delete-next-character")
call_command ("edit-revert")
call_command ("file-save")
call_command ("file-quit")
