call_command ("move-next-character", "4")
call_command ("edit-select-on", "point")
call_command ("forward-line", "2")
call_command ("edit-select-other-end")
insert_string ("f")
call_command ("file-save")
call_command ("file-quit")
