call_command ("edit-select-on", "point")
call_command ("forward-line", "2")
call_command ("edit-kill-selection", "point", "mark")
call_command ("forward-line", "3")
call_command ("edit-paste")
call_command ("file-save")
call_command ("file-quit")
