call_command ("move-next-line")
call_command ("move-next-line")
call_command ("edit-insert-tab")
call_command ("edit-insert-tab")
insert_string ("tab")
call_command ("file-save")
call_command ("file-quit")
