call_command ("move-end-line")
insert_string (" I am now going to make the line sufficiently long that I can wrap it.")
call_command ("edit-wrap-paragraph")
call_command ("edit-undo")
insert_string ("a")
call_command ("file-save")
call_command ("file-quit")
