call_command ("forward-char", "6")
call_command ("insert", ")")
call_command ("beginning-of-line")
call_command ("insert", "(")
call_command ("beginning-of-line")
call_command ("forward-sexp")
call_command ("insert", "a")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
