call_command ("help-key", "\\C-f")
call_command ("other-window", "1")
call_command ("edit-select-on", "point")
call_command ("forward-line")
call_command ("edit-copy", "mark", "point")
call_command ("other-window", "-1")
call_command ("edit-paste")
call_command ("file-save")
call_command ("file-quit")
