call_command ("indent-for-tab-command")
call_command ("forward-line")
call_command ("beginning-of-line")
call_command ("indent-for-tab-command")
call_command ("forward-line", "2")
call_command ("beginning-of-line")
call_command ("indent-for-tab-command")
call_command ("forward-line")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
