call_command ("indent-for-tab-command")
call_command ("forward-line")
call_command ("move-start-line")
call_command ("indent-for-tab-command")
call_command ("forward-line", "2")
call_command ("move-start-line")
call_command ("indent-for-tab-command")
call_command ("forward-line")
call_command ("file-save")
call_command ("file-quit")
