call_command ("forward-line", "2")
call_command ("indent-relative")
call_command ("insert", "f")
call_command ("indent-relative")
call_command ("insert", "fffff")
call_command ("indent-relative")
call_command ("insert", "aaa")
call_command ("file-save")
call_command ("file-quit")
