call_command ("forward-line", "2")
call_command ("indent-relative")
call_command ("insert", "f")
call_command ("indent-relative")
call_command ("insert", "fffff")
call_command ("indent-relative")
call_command ("insert", "aaa")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
