call_command ("forward-line")
call_command ("forward-word", "2")
call_command ("kill-line")
call_command ("forward-line", "2")
call_command ("kill-line", "-1")
call_command ("forward-line", "-2")
call_command ("end-of-line")
call_command ("kill-line", "0")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
