call_command ("forward-word")
call_command ("insert", "(")
call_command ("forward-word", "3")
call_command ("insert", ")")
call_command ("backward-word", "2")
call_command ("backward-char", "5")
call_command ("mark-sexp")
call_command ("kill-region", "point", "mark")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
