call_command ("move-end-line")
call_command ("move-previous-character")
call_command ("move-previous-character")
call_command ("edit-delete-previous-character")
call_command ("file-save")
call_command ("file-quit")
