call_command ("move-end-file")
call_command ("move-previous-line")
call_command ("move-previous-line")
call_command ("move-previous-line")
insert_string ("a")
call_command ("file-save")
call_command ("file-quit")
