; FIXME: Next line should not be needed
(setq sentence-end-double-space nil)
(set-mark (point))
(forward-line 2)
(kill-region (point) (mark))
(yank)
(yank)
(open-line 1)
(forward-line)
(yank)
(forward-line)
(set-fill-column 3)
(fill-paragraph)
(forward-line -3)
(set-fill-column 12)
(fill-paragraph)
(forward-line -6)
(end-of-line)
(set-fill-column 33)
(fill-paragraph)
(save-buffer)
(save-buffers-kill-emacs)
