call_command ("edit-select-on", "point")
call_command ("move-next-line", "2")
call_command ("edit-kill-selection", "point", "mark")
call_command ("edit-paste")
call_command ("edit-paste")
call_command ("edit-insert-newline")
call_command ("move-previous-character")
call_command ("move-next-line")
call_command ("edit-paste")
call_command ("move-next-line")
call_command ("set-fill-column", "3")
call_command ("edit-wrap-paragraph")
call_command ("move-next-line", "-3")
call_command ("set-fill-column", "12")
call_command ("edit-wrap-paragraph")
call_command ("move-next-line", "-6")
call_command ("move-end-line")
call_command ("set-fill-column", "33")
call_command ("edit-wrap-paragraph")
call_command ("file-save")
call_command ("file-quit")
