-- FIXME: Next line should not be needed
call_command ("setq", "sentence-end-double-space", "nil")
call_command ("set-mark", "point")
call_command ("forward-line", "2")
call_command ("kill-region", "point", "mark")
call_command ("yank")
call_command ("yank")
call_command ("open-line", "1")
call_command ("forward-line")
call_command ("yank")
call_command ("forward-line")
call_command ("set-fill-column", "3")
call_command ("fill-paragraph")
call_command ("forward-line", "-3")
call_command ("set-fill-column", "12")
call_command ("fill-paragraph")
call_command ("forward-line", "-6")
call_command ("end-of-line")
call_command ("set-fill-column", "33")
call_command ("fill-paragraph")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
