call_command ("set-mark", "point")
call_command ("forward-line", "4")
call_command ("shell-command-on-region", "mark", "point", "sort", "t")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
