\input texinfo   @c -*-texinfo-*-
@setfilename zee.info
@settitle The Zee Manual

@dircategory Text editors
@direntry
* Zee: (zee).                 Zee text editor.
@end direntry

@c If "finalout" is commented out, the printed output will show
@c black boxes that mark lines that are too long.  Thus, it is
@c unwise to comment it out when running a master in case there are
@c overfulls which are deemed okay.

@iftex
@c @finalout
@end iftex

@setchapternewpage odd

@titlepage
@title The Zee Manual
@subtitle for Zee version 0.5
@subtitle February 2006
@author Reuben Thomas

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2003-2006 Reuben Thomas
Copyright @copyright{} 2005 Alistair Turnbull
Copyright @copyright{} 1997-2004 Sandro Sigala
Copyright @copyright{} 2004 David A. Capello
@end titlepage

@c ---------------------------------------------------------------------------
@node Top, Overview, (dir), (dir)

This is the @emph{Zee} manual.

Zee is a customizable, self-documenting real-time display editor.

@menu
* Overview::                    An overview of the Zee editor.
* Features::                    The characteristics of Zee.
* Invoking Zee::               Command line options that you can give to Zee.
* Initialization file::         The ``.zee'' initialization file.
* Key names::                   How the keys are named.
* Functions::                   The list of functions.
* Variables::                   The list of variables.
* Bug reports::                 How to report a bug.
@end menu

@c ---------------------------------------------------------------------------
@node Overview, Features, Top, Top
@chapter Overview

The @emph{Zee} editor is written entirely in @emph{@w{ANSI C}}.
It should run on any POSIX system. It has also been ported to @emph{EPOC}.

@c ---------------------------------------------------------------------------
@node Features, Invoking Zee, Overview, Top
@chapter Features

@itemize -
@item Small but fast and powerful.
It is very useful for small footprint installations (e.g. on floppy disk)
or quick editing sessions.
@item 8-bit clean.
Zee can operate with binary files.
@item Looks familiar.
Most Zee key sequences and function names are identical to standard CUA
ones (as used in Microsoft Windows, Mac OS and other common GUIs).
@item Multi buffer editing with multi level undo.
Zee can open an infinite number of files and can record an infinite
sequence of undo operations (limited only by the amount of free memory).
@item Multi window.
Zee can display multiple windows on the screen.
@item Minibuffer completion.
This works for @kbd{M-x} commands.
@item Auto fill (word wrap).
Zee automatically breaks the lines when they become too wide (if the
@i{Auto Fill Mode} is enabled).
@item Auto line ending detection.
When a file is loaded, its line ending is detected automatically
according to the first end of line, either LF, CR, CRLF or LFCR.  Files with
mixed line endings will not be corrupted, but the line breaks will not be correctly
displayed.
@end itemize

@c ---------------------------------------------------------------------------
@node Invoking Zee, Initialization file, Features, Top
@chapter Invoking Zee

The options are as follows:

@include zee_opts.texi

@c ---------------------------------------------------------------------------
@node Initialization file, Key names, Invoking Zee, Top
@chapter Initialization file

When Zee is started, it normally loads the @file{.zee} file in your
home directory. We call this file your ``initialization file'' because
it specifies how to initialize Zee for you. You can use the command
line switch @samp{--no-init-file} to tell Zee not to load the initialization file.

@menu
* File syntax::                 The initialization file syntax.
* Sample file::                 A sample initialization file.
@end menu

@c ---------------------------------------------------------------------------
@node File syntax, Sample file, Initialization file, Initialization file
@section File syntax

The initialization file is a sequence of commands.
The file is most commonly used to initialize
variables; see the next subsection for an example.

@c ---------------------------------------------------------------------------
@node Sample file,  , File syntax, Initialization file
@section A sample file

This is the initialization file that comes with the Zee sources.

@include dotzee.texi

@c ---------------------------------------------------------------------------
@node Key names, Functions, Initialization file, Top
@chapter Key names

This table contains the names of the keys that are used in Zee.

@table @key
@item SPC
Space
@item RET
Return
@item LFD
Linefeed
@item TAB
Tab
@item BS
Backspace
@item ESC
Escape
@item DEL
Delete
@item CTRL
Control
@item META
Meta (also known as @key{EDIT} or @key{ALT} on some keyboards).
@end table

In key combinations, like @kbd{M-g}, the @kbd{M-} prefix means hold the
@key{META} (or @key{EDIT} or @key{ALT}) key down while typing @kbd{g}.
The combination @kbd{C-x} means hold the @key{CTRL} key down while
typing @kbd{x}.

@c ---------------------------------------------------------------------------
@node Functions, Variables, Key names, Top
@chapter Functions

This table contains the full list of available functions that can be
called with the @kbd{M-x} key (please note that most functions have a
key binding anyway).

@include zee_funcs.texi

@c ---------------------------------------------------------------------------
@node Variables, Bug reports, Functions, Top
@chapter Variables

This table contains the full list of available variables, that can be
modified at run-time with the @samp{set-variable} function or set at start-up
in the @file{.zee} initialization file.

Please note that some variables may be not available depending
on the compilation options given to @samp{configure}.

@include zee_vars.texi

@c ---------------------------------------------------------------------------
@node Bug reports,  , Variables, Top
@chapter Bug reports

Any questions, comments, or bug reports should be sent to the
developers at @email{rrt@@sc3d.org}, or even better,
filed in the relevant tracker at @uref{http://sourceforge.net/projects/zee/}.

@contents

@bye

Local Variables:
compile-command: "texi2dvi zee.texi"
End:
