call_command ("move-next-character")
call_command ("move-next-character")
call_command ("move-next-character")
call_command ("move-next-character")
call_command ("move-next-line")
call_command ("move-next-line")
call_command ("move-next-line")
call_command ("insert", "a")
call_command ("file-save")
call_command ("file-quit")
