call_command ("forward-char")
call_command ("forward-char")
call_command ("forward-char")
call_command ("forward-char")
call_command ("next-line")
call_command ("next-line")
call_command ("next-line")
call_command ("insert", "a")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
