-- undo in Emacs undoes everything from the start of the script (cf. fill-paragraph_2.el)
call_command ("delete-char", "1")
call_command ("delete-char", "1")
call_command ("delete-char", "1")
call_command ("delete-char", "1")
call_command ("undo")
call_command ("undo")
call_command ("undo")
call_command ("save-buffer")
call_command ("save-buffers-kill-emacs")
